// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4Wpvttzz6WRh-pIiHYicUc2fAneh2ME',
    appId: '1:580724856781:web:2b974f59e826c7e39a9684',
    messagingSenderId: '580724856781',
    projectId: 'portfolio-fb31e',
    authDomain: 'portfolio-fb31e.firebaseapp.com',
    storageBucket: 'portfolio-fb31e.appspot.com',
    measurementId: 'G-NPRH4Q3GN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi_3g-AdXDdieb1IxoxA4fByTXCPA5Ihs',
    appId: '1:580724856781:android:c3c4778a96c9633a9a9684',
    messagingSenderId: '580724856781',
    projectId: 'portfolio-fb31e',
    storageBucket: 'portfolio-fb31e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_BTjLf3ZCy_sn4oNxdvXt0dXb_KX5bU4',
    appId: '1:580724856781:ios:ba7aba67bc90a57f9a9684',
    messagingSenderId: '580724856781',
    projectId: 'portfolio-fb31e',
    storageBucket: 'portfolio-fb31e.appspot.com',
    iosBundleId: 'com.becoder.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_BTjLf3ZCy_sn4oNxdvXt0dXb_KX5bU4',
    appId: '1:580724856781:ios:bd88ed90f0982e5c9a9684',
    messagingSenderId: '580724856781',
    projectId: 'portfolio-fb31e',
    storageBucket: 'portfolio-fb31e.appspot.com',
    iosBundleId: 'com.becoder.portfolio.RunnerTests',
  );
}
